### ISSUE TITLE
After installing a WAD, using B to return to Wii-Mod-Lite menu fails

### ISSUE THREAD

**Issue by gingerbeardman** [RiiConnect24/Wii-Mod-Lite#3]
Steps to reproduce 
1. install WAD
2. press any button to continue
3. press B (go up a directory)
4. press B (return to main menu)

Expected
- should return to WML main menu

Actual
- error visible in bottom right of screen
> `(2)   File operationsError:: Fai`
- WML is crashed, need to power off Wii to recover

**Comment by larsenv** [comment]
Thanks for the well-written issue, but unfortunately I can't fix it since we don't have the source code for this program at this time. Sorry about that.

**Comment by gingerbeardman** [comment]
Just to note, this was foxed by removing some "empty" titles from my Wii for games that I had once installed many years ago. One of them (throwing a TMDsize error) seemed to be the cause of this crash.

**Comment by GianfrancoFrau** [comment]
I have the same issue. Any help?

**Comment by larsenv** [comment]
@GianfrancoFrau if you're installing a WAD, just press the HOME Button when you're done with it after pressing a button when the WAD has been installed successfully.

**Comment by GianfrancoFrau** [comment]
@larsenv thanks a lot! So there isn't a fix to let it go back pressing B?

**Comment by larsenv** [comment]
@GianfrancoFrau I don't know of one.

**Comment by gingerbeardman** [comment]
> I have the same issue. Any help?

Regarding my answer above:

1. Install Priiloader
2. Make a full backup of your NAND if that's what you're working on.
3. Use Any Title Deleter to remove "empty" titles

What are empty titles?
 - titles that are installed that do not show on the menu screen
 - titles that are installed with zero content
 - watch out because some saves may look like titles

Let us know how you get on!
