### ISSUE TITLE
After installing bogus wads I get this error with Wii Mod Lite using wad2bin

### ISSUE THREAD

**Issue by msimplay** [RiiConnect24/Wii-Mod-Lite#4]
After installing bogus wads I get this error with Wii Mod Lite

![106344053-858f9100-62a0-11eb-8e55-c040a0236a1c](https://user-images.githubusercontent.com/49412623/106351173-82ad9400-62d2-11eb-9df6-9a818967240e.jpg)

Error:: Failed to get TMD size. tid = 2814807XXXXXXXX

Then freezes the console and I have to reboot

However I am able to use Wii Mod 3.2 and can use wad manager there

The author of wad2bin says

![Screenshot_2021-01-30 After installing bogus wads I get this error with Wii Mod Lite · Issue #6 · DarkMatterCore wad2bin(1)](https://user-images.githubusercontent.com/49412623/106351230-e5069480-62d2-11eb-9b35-7f8e3640456d.png)

Please look into this

**Comment by KcrPL** [comment]
We're not the creators of Wii Mod Lite and therefore, we don't have the source code for it. We only host it here.

There's nothing we can do. Closing.

**Comment by msimplay** [comment]
But it's in your script recommends installing bogus wads and its in your package that you recommend using Wii Mod Lite that clearly conflicts with wad2bin.
There are other Wad installers that don't conflict

**Comment by KcrPL** [comment]
Interresting, for me it works like a charm.

**Comment by msimplay** [comment]
I'm not really sure what causes it but I have searched it on Google and saw one other person it happened to with no real fix other than to use another wad manager or don't install bogus wads

**Comment by Damaj301damaj-lol** [comment]
> We're not the creators of Wii Mod Lite and therefore, we don't have the source code for it. We only host it here.
> 
> There's nothing we can do. Closing.

Why does this repo excit lol
