### ISSUE TITLE
WML freezes when returning to loader if loader is OHBC, even with title ID change

### ISSUE THREAD

**Issue by WiiExpertise** [RiiConnect24/Wii-Mod-Lite#5]
I have the OHBC (open source Homebrew Channel) installed on my Wii. I changed the title id to LULZ (matching the original HBC) to help in compatibility with homebrew. However, even with this change, if I load Wii Mod Lite through it and then press home to return to loader, it freezes. I know it did not do this with the normal Homebrew Channel.

I doubt it makes a difference, but my Wii does have DARKCORP installed.

**Comment by urmum-69** [comment]
unfortunately, we don't have the source code for wii mod lite and there is nothing anyone can do
you should use a different wad manager I suppose
