### ISSUE TITLE
Error when trying to install the Korean Mario Kart Channel on a US console.

### ISSUE THREAD

**Issue by Sync219** [RiiConnect24/Wii-Mod-Lite#7]
Hello! I've been trying to use this to install the Korean Mario Kart Channel to my NTSC-U Wii and it gives me error -1022 but on Dolphin it works perfect without any issues.

**Comment by Peter0x44** [comment]
Perhaps try pressing - to uninstall it, then try installing again.
Even if this is a legitimate bug on the end of Wii Mod Lite, there is no source code for it so it can't be fixed.

**Comment by larsenv** [comment]
Why in the world are you trying to install the Korean WAD on a US console???
